### ISSUE TITLE
Prototipar Interfaz Dashboard de Opciones

### ISSUE THREAD

**Issue by mateovlz** [mateovlz/dsSeverityAccidents#25]
## Menú de Opciones de Interfaces

Se requiere prototipar una interfaz que se despliegue toda la información, con las opciones de integración para la selección de tipo  de `Dashboards`. 

### Estructura de la interfaz: &#11088;
La interface deberá contar con lo siguiente:
- El header de la interfaz debe contener lo siguiente:
    - En la parte izquierda superior el icono del menú tipo hamburguesa 
       - ![image](https://user-images.githubusercontent.com/39438103/137650647-81ad9d68-cd54-4657-a5aa-667428318d23.png)
    - En el centro se deberá ubicar el logo del aplicativo `ISeverity`
      - ![image](https://user-images.githubusercontent.com/39438103/137650564-d0826dc7-fa06-4282-86ca-2eb2a2bbfea4.png)
    - En la parte izquierda debajo y con espacio de ancho del icono de hamburguesa se debe ubica un hipervínculo que redireccione al menú principal con el siguiente texto `< Inicio`
    - El color de fondo de toda la interfaz deberá ser `#FFFFFF`
- El contenido principal de la interfaz deberá tener lo siguiente:
    -  Sección 1 Boton en formato de texto para retornar al inicio.
        - Fuente  **Fount:** `Montserrat`
        - Style: `Medium`
        - Tamaño **Size:** `20`
        - Texto: `< Inicio`
    -  Sección 2 constara de un titulo  en la parte superior - centrado
        -  Color de fuente **Color:** `#000000`
        -  Fuente  **Fount:** `Montserrat`
        - Style: `SemiBold`
        -  Tamaño **Size:** `50`
        - Texto: Desbordas
    - Sección 3 Constara de un card con cuatro componentes dentro en el formato 2x2
        - fondo **Color:** `#FFFFFF`
        -  Componentes
            -  Card 1 superior 
                - fondo **Background:** `#CD113B`
                     - Color de fuente **Color:** `#000000`
                     - Fuente  **Fount:** `Montserrat`
                     - Style: `Medium`
                     - Tamaño **Size:** `24`
                     - Texto: Siniestros Viales por Elementos de Seguridad
            -  Card 2 superior 
                - fondo **Background:** `#52006A`
                     - Color de fuente **Color:** `#000000` 
                     - Fuente  **Fount:** `Montserrat`
                     - Style: `Medium`
                     - Tamaño **Size:** `24`
                     - Texto Siniestros Viales Por Gravedad  
            -  Card 3 inferior
                - fondo **Background:** `#9A5E7F`
                     - Color de fuente **Color:** `#000000`
                     - Fuente  **Fount:** `Montserrat`
                     - Style: `Medium`
                     - Tamaño **Size:** `24`
                     - Texto: Siniestros Viales Por Localidades
            -  Card 1 inferior
                - fondo **Background:** `#FF7600`
                     - Color de fuente **Color:** `#000000`
                     - Fuente  **Fount:** `Montserrat`
                     - Style: `Medium`
                     - Tamaño **Size:** `24`
                     - Texto: Siniestros Viales Por Tipo de Horario
- Al finalizar el contenido principal en la parte del footer se deberá tener lo siguiente:
    - Fondo **backgroung:** `#000000`. 
    -  Color fuente **Color:** `#FFFFFF`
    -  Text: Powered By ISeverity (Mateo Vélez - Santiago Leon) 

### Prototipado &#x1F44D;
![Interface de dashborad de opciones](https://user-images.githubusercontent.com/85606458/137645652-bf5613a2-16fc-427b-8a58-7a35b13680c7.png)

**Comment by Thiago97SLA** [comment]
Documentación del requerimiento completa `APROBADO` 🔥

**Comment by mateovlz** [comment]
Prototipado realizado acorde al requerimiento `APROBADO` 🔥
