### ISSUE TITLE
Prototipar Interfaz de Contacto

### ISSUE THREAD

**Issue by mateovlz** [mateovlz/dsSeverityAccidents#32]
##  Prototipar Interfaz de Contacto
Se requiere prototipar una interfaz que se desplieguen un formulario en el que el usuario pueda comunicar sus inquietudes frente al aplicativo web. 

### Estructura de la interfaz: &#11088;
La interface deberá contar con lo siguiente:
- El header de la interfaz debe contener lo siguiente:
    - En la parte izquierda superior el icono del menú tipo hamburguesa 
       - ![image](https://user-images.githubusercontent.com/39438103/137650647-81ad9d68-cd54-4657-a5aa-667428318d23.png)
    - En el centro se deberá ubicar el logo del aplicativo `ISeverity`
      - ![image](https://user-images.githubusercontent.com/39438103/137650564-d0826dc7-fa06-4282-86ca-2eb2a2bbfea4.png)
    - En la parte izquierda debajo y con espacio de ancho del icono de hamburguesa se debe ubica un hipervínculo que redireccione al menú principal con el siguiente texto `< Inicio`
    - El color de fondo de toda la interfaz deberá ser `#FFFFFF`
- El contenido principal de la interfaz deberá tener lo siguiente:
    -  Sección 1 Boton en formato de texto para retornar al inicio.
        - Fuente Fount: Montserrat
        - Tamaño Size: 20
        - Texto: `< Inicio`
     -  Sección 2 constara de un titulo  en la parte superior -  centrado
        - Color de fuente **Color:** `#000000`
        - Fuente  **Fount:** `Montserrat`
        - Style: `SemiBold`
        - Tamaño **Size:** `50`
        - Texto: Contactar
    - Sección 3  Sección 3 Constara de un card  con un formulario.
        - fondo **Color:** `#FFFFFF`
        -  Formulario contara de 4 indicies, 4 input y 1 botón
            -  características del Índice nombre
                - Color de fuente **Color:** `#000000`
                - Fuente  **Fount:** `Montserrat`
                - Style: `Medium`
                - Tamaño **Size:** `24`
                - Texto: Nombre
            -  características del input de nombre
               -   Fondo **Color:** `#FFFFFF`
               -  Ancho **width:** `70%`
               - Alto **heigth:** `50px`
            -  características del email
                -  Color de fuente **Color:** `#000000`
                - Fuente  **Fount:** `Montserrat`
                - Style: `Medium`
                - Tamaño **Size:** `24`
                - Texto: Nombre
            -  características del input de email
               - Fondo **Color:** `#FFFFFF`
               - Ancho **width:** `70%`
               - Alto **heigth:** `50px`
            -  características del asunto
                - Color de fuente **Color:** `#000000`
                - Fuente  **Fount:** `Montserrat`
                - Style: `Medium`
                - Tamaño **Size:** `24`
                - Texto: Nombre
            -  características del input de asunto
               - Fondo **Color:** `#FFFFFF`
               - Ancho **width:** `70%`
               - Alto **heigth:** `50px`  
            -  características del mensaje
                - Color de fuente **Color:** `#000000`
                - Fuente  **Fount:** `Montserrat`
                - Style: `Medium`
                - Tamaño **Size:** `24`
                - Texto: Nombre
            -  características del input de mensaje
               - Fondo **Color:** `#FFFFFF`
               - Ancho **width:** `70%`
               - Alto **heigth:** `170
            - Botón  de enviar deberá contar con las siguientes de  características 
               - Fondo **Color:** `#FF7600`
               - Ancho **width:** `113px`
               - Alto **heigth:** `50px`
               - Color de fuente **Color:** `#FFFFFF`
               - Fuente  **Fount:** `Montserrat`
                - Style: `Medium`
- Al finalizar el contenido principal en la parte del footer se deberá tener lo siguiente:
    - Fondo **backgroung:** `#000000`. 
    -  Color fuente **Color:** `#FFFFFF`
    -  Text: Powered By ISeverity (Mateo Vélez - Santiago Leon)
    
### Prototipado &#x1F44D;
![Prototipar Interfaz de contactar (1)](https://user-images.githubusercontent.com/85606458/137646393-a60e9503-4c50-4501-8542-3e75b0016386.png)

**Comment by Thiago97SLA** [comment]
Documentación del requerimiento completa `APROBADO` 🔥

**Comment by Thiago97SLA** [comment]
Prototipado realizado acorde al requerimiento `APROBADO` 🔥
