### ISSUE TITLE
Prototipar Dashboard Siniestros Viales por Tipo Vehiculo

### ISSUE THREAD

**Issue by mateovlz** [mateovlz/dsSeverityAccidents#40]
##  Dashboard Siniestros Viales por Tipo Vehiculo

Se requiere prototipar una interfaz donde se despliegue todos los resultados de los analisis realizados por el producto de datos acerca agrupados por tipo de vehiculo en esta interfaz se encontraran los graficos generados donde el usuario podra realizar analisis en los datos presentados.

### En esta interfaz se encontraran los siguientes graficos 📊📉📈
1. Cantidad de Personas Involucradas en Siniestros Viales por Modelo de Vehiculo en cada año.
2. Cantidad de Personas Involucradas en Siniestros Viales por Modelo de Vehiculo del año 2019.
3. Cantidad de Personas Involucradas en Siniestros Viales por Modelo de Vehiculo del año 2018.
4. Cantidad de Personas Involucradas en Siniestros Viales por Modelo de Vehiculo del año 2017.

### Estructura de la interfaz: &#11088;
La interfaz debe contar con lo siguiente:
- El header de la interfaz debe contener lo siguiente:
   - En la parte izquierda superior el icono del menú tipo hamburguesa 
      - ![image](https://user-images.githubusercontent.com/39438103/137650647-81ad9d68-cd54-4657-a5aa-667428318d23.png)
    - En el centro se deberá ubicar el logo del aplicativo `ISeverity`
       - ![image](https://user-images.githubusercontent.com/39438103/137650564-d0826dc7-fa06-4282-86ca-2eb2a2bbfea4.png)
    - En la parte izquierda debajo y con espacio de ancho del icono de hamburguesa se debe ubica un hipervínculo que redireccione al menú principal con el siguiente texto `< Inicio`
    - El color de fondo de toda la interfaz deberá ser `#FFFFFF`
- El contenido principal de la interfaz deberá tener lo siguiente:
     - El estilo generico de los `cards `para las interfaces sera el siguiente:
        -  Estilos de Bordes: `box-shadow: 2px 2px 19px rgba(0, 0, 0, 0.25); border-radius: 15px;`
     - Deberá tener un titulo justificado en el centro el cual tendrá el siguiente
        - Color de fuente Color: `#000000` 
        - Fuente: `Montserrat`
        - Tamaño: `24`
        - Texto: `Siniestros Viales por Tipo de Vehiculo` 
     - Se debera tener una card en la cual se hara una corta descripción de lo que se encontrara en la interfaz y tendra lo siguiente.
        - Color de fondo: `#FFE5B1`
        - Color de fuente Color: `#000000` 
        - Fuente: `Poppins`
        - Style: `Medium`
        - Tamaño: `20`
        - Texto: `En este tablero se podra observar todos los graficos y resultados generados a traves del producto de datos en de los siniestros viales por tipo de vehiculo.(Para observar los graficos de mejor manera dar click en el grafico)`  
     - Se debera tener cuatro secciones donde tendra lo siguiente:
     - La primera seccion debera ser una card el cual tendra un titulo justificado hacia el centro en la parte superior y despues tendra la imagen del grafico `1` en formato `.png` y tendra lo siguiente:
        - Color de fondo: `#FFFFFF`
        - Color de fuente Color: `#000000` 
        - Fuente: `Poppins`
        - Style: `Medium`
        - Tamaño: `24`
        - Texto: `Cantidad de Personas Involucradas en Siniestros Viales por Modelo de Vehiculo en cada año.`  
        - Grafico: `No 1`
      - La segunda seccion debera ser una card el cual tendra un titulo justificado hacia el centro en la parte superior y despues tendra la imagen del grafico `No 2` en formato `.png` y tendra lo siguiente:
        - Color de fondo: `#FFFFFF`
        - Color de fuente Color: `#000000` 
        - Fuente: `Poppins`
        - Style: `Medium`
        - Tamaño: `24`
        - Texto: `Cantidad de Personas Involucradas en Siniestros Viales por Modelo de Vehiculo del año 2019.`  
        - Grafico: `No 2`
      - La tercera seccion debera ser una card el cual tendra un titulo justificado hacia el centro en la parte superior y despues tendra la imagen del grafico `No 3` en formato `.png` y tendra lo siguiente:
        - Color de fondo: `#FFFFFF`
        - Color de fuente Color: `#000000` 
        - Fuente: `Poppins`
        - Style: `Medium`
        - Tamaño: `24`
        - Texto: `Cantidad de Personas Involucradas en Siniestros Viales por Modelo de Vehiculo del año 2018.`  
        - Grafico: `No 3`
     - La cuarta seccion debera ser una card el cual tendra un titulo justificado hacia el centro en la parte superior y despues tendra la imagen del grafico `No 4` en formato `.png` y tendra lo siguiente:
        - Color de fondo: `#FFFFFF`
        - Color de fuente Color: `#000000` 
        - Fuente: `Poppins`
        - Style: `Medium`
        - Tamaño: `24`
        - Texto: `Cantidad de Personas Involucradas en Siniestros Viales por Modelo de Vehiculo del año 2017.`  
        - Grafico: `No 4`
- Al finalizar el contenido principal en la parte del footer se debera tener lo siguiente:
    - Color de fondo: `#000000`. 
    -  Color fuente: `#FFFFFF`
    -  Texto: Powered By ISeverity (Mateo Vélez - Santiago Leon) 

### Prototipado &#x1F44D;

![Interface de dashborad de siniestros viales por tipo de vehiculo](https://user-images.githubusercontent.com/39438103/137659713-ec872561-7857-49f4-9252-8c4d2f7d07ec.png)

**Comment by Thiago97SLA** [comment]
Documentación del requerimiento completa `APROBADO` 🔥

**Comment by Thiago97SLA** [comment]
Prototipado realizado acorde al requerimiento APROBADO 🔥
